import {FolderComponent} from "../io_components/FolderComponent.slint";
import { FileData } from "../file_data/FileData.slint";
import {IoWindowAdapter} from "../adapters/IoWindowAdapter.slint";
import { ScrollView } from "std-widgets.slint";

export component FoldersViewport {
    in-out property <[FileData]> folders;

    callback open_folder(string);

    min-width: 50px;
    min-height: 50px;

    ScrollView {
        VerticalLayout {
            for folder in folders: comp:= FolderComponent {
                folder: folder;
                open_folder(path) => {
                    root.open_folder(path);
                }
            }

        }
    }
}